In [1]:
#1.Write a Python Program to Add Two Matrices?
# Program to add two matrices using list comprehension

X = [[1,2,3],
    [4 ,5,6],
    [7 ,8,9]]

Y = [[9,8,7],
    [6,5,4],
    [3,2,1]]

result = [[X[i][j] + Y[i][j] for j in range
(len(X[0]))] for i in range(len(X))]

for r in result:
    print(r)


[10, 10, 10]
[10, 10, 10]
[10, 10, 10]


In [4]:
#2. Write a Python Program to Multiply Two Matrices?
# Program to multiply two matrices (vectorized implementation)
import numpy as np
# take a 3x3 matrix
A = [[12, 7, 3],
    [4, 5, 6],
    [7, 8, 9]]

# take a 3x4 matrix
B = [[5, 8, 1, 2],
    [6, 7, 3, 0],
    [4, 5, 9, 1]]

# result will be 3x4

result= [[0,0,0,0],
        [0,0,0,0],
        [0,0,0,0]]

result = np.dot(A,B)

for r in result:
    print(r)



[114 160  60  27]
[74 97 73 14]
[119 157 112  23]


In [5]:
#3.Write a Python Program to Transpose a Matrix?
N = 4

# Finds transpose of A[][] in-place
def transpose(A):

    for i in range(N):
        for j in range(i+1, N):
            A[i][j], A[j][i] = A[j][i], A[i][j]

# driver code
A = [ [1, 1, 1, 1],
    [2, 2, 2, 2],
    [3, 3, 3, 3],
    [4, 4, 4, 4]]

transpose(A)

print("Modified matrix is")
for i in range(N):
    for j in range(N):
        print(A[i][j], " ", end='')
    print()


Modified matrix is
1  2  3  4  
1  2  3  4  
1  2  3  4  
1  2  3  4  


In [6]:
#4.Write a Python Program to Sort Words in Alphabetic Order?

my_str = "Hello this Is an Example With cased letters"

# To take input from the user
#my_str = input("Enter a string: ")

# breakdown the string into a list of words
words = [word.lower() for word in my_str.split()]

# sort the list
words.sort()

# display the sorted words

print("The sorted words are:")
for word in words:
   print(word)

The sorted words are:
an
cased
example
hello
is
letters
this
with


In [7]:
#5. Write a Python Program to Remove Punctuation From a String?
# define punctuation
punctuations = '''!()-[]{};:'"\,<>./?@#$%^&*_~'''

my_str = "Hello!!!, he said ---and went."

# To take input from the user
# my_str = input("Enter a string: ")

# remove punctuation from the string
no_punct = ""
for char in my_str:
   if char not in punctuations:
       no_punct = no_punct + char

# display the unpunctuated string
print(no_punct)

Hello he said and went
